/**
 * MVP schema per plan contract C2 (mvp-scope D2: two-state model).
 *
 * Working state = `notepages` row fields + `blocks` rows (normalized).
 * Public state  = `notepages.publishedDoc` JSON snapshot, written only
 * by the explicit update-public action. Public readers never read the
 * working-state tables directly.
 */
import { index, integer, primaryKey, sqliteTable, text } from 'drizzle-orm/sqlite-core';

// better-auth tables (user/session/account/verification), generated by
// @better-auth/cli from src/auth.ts config — regenerate there, not here.
export * from './auth-schema';

export const notepages = sqliteTable('notepages', {
  id: text('id').primaryKey(),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull().default('Untitled'),
  visibility: text('visibility', { enum: ['private', 'public'] })
    .notNull()
    .default('private'),
  gravityEnabled: integer('gravity_enabled', { mode: 'boolean' }).notNull().default(true),
  publishedDoc: text('published_doc'),
  publishedHtml: text('published_html'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
});

export const blocks = sqliteTable(
  'blocks',
  {
    // Block instance identity is notepage-scoped (client-generated ids
    // are only unique within a page) → composite PK, not a global one.
    id: text('id').notNull(),
    notepageId: text('notepage_id')
      .notNull()
      .references(() => notepages.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull(),
    col: integer('col').notNull(),
    row: integer('row').notNull(),
    colSpan: integer('col_span').notNull(),
    rowSpan: integer('row_span').notNull(),
    content: text('content').notNull(),
  },
  (t) => [primaryKey({ columns: [t.notepageId, t.id] }), index('idx_blocks_notepage').on(t.notepageId)],
);

/**
 * Content-addressed blob registry (mvp2 M2-D3): hash = sha256 of bytes,
 * files live in the blob dir keyed by hash, rows are metadata only.
 * Immutable: a hash is never re-written; no GC in MVP-2 (surfaced debt).
 */
export const blobs = sqliteTable('blobs', {
  hash: text('hash').primaryKey(),
  mimeType: text('mime_type').notNull(),
  size: integer('size').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
});

export type NotepageRow = typeof notepages.$inferSelect;
export type BlockRow = typeof blocks.$inferSelect;

/** Shape of the publishedDoc JSON snapshot. */
export type PublishedDoc = {
  title: string;
  gravityEnabled: boolean;
  blocks: Array<{
    id: string;
    kind: string;
    col: number;
    row: number;
    colSpan: number;
    rowSpan: number;
    content: unknown;
  }>;
  publishedAt: number;
};
