/**
 * MVP schema per plan contract C2 (mvp-scope D2: two-state model).
 *
 * Working state = `notepages` row fields + `blocks` rows (normalized).
 * Public state  = `notepages.publishedDoc` JSON snapshot, written only
 * by the explicit update-public action. Public readers never read the
 * working-state tables directly.
 */
import { index, integer, primaryKey, sqliteTable, text } from 'drizzle-orm/sqlite-core';

// better-auth tables (user/session/account/verification), generated by
// @better-auth/cli from src/auth.ts config — regenerate there, not here.
export * from './auth-schema';

/**
 * Workspace organization (owner decision 2026-06-12): a forest of
 * folders + pages, encoded as data (parent_id / folder_id), never as
 * runtime DDL. Organization is author-side metadata: the public tree
 * is a live read-time projection (pruned to public+published pages) —
 * existence in the public tree is gated by explicit publish/visibility
 * actions, position is metadata (deliberate, recorded deviation from
 * strict two-state).
 */
export const folders = sqliteTable('folders', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  parentId: text('parent_id'),
  sortKey: integer('sort_key').notNull().default(0),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
});

export const notepages = sqliteTable('notepages', {
  id: text('id').primaryKey(),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull().default('Untitled'),
  visibility: text('visibility', { enum: ['private', 'public'] })
    .notNull()
    .default('private'),
  gravityEnabled: integer('gravity_enabled', { mode: 'boolean' }).notNull().default(true),
  /** Per-page theme pin; null = follow the instance theme [ADR-0024]. */
  themeId: text('theme_id'),
  /** Author-picked page background JSON {color?, blobHash?} (M6-D4);
   * null = theme canvas. */
  background: text('background'),
  folderId: text('folder_id'),
  sortKey: integer('sort_key').notNull().default(0),
  publishedDoc: text('published_doc'),
  publishedHtml: text('published_html'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
});

export const blocks = sqliteTable(
  'blocks',
  {
    // Block instance identity is notepage-scoped (client-generated ids
    // are only unique within a page) → composite PK, not a global one.
    id: text('id').notNull(),
    notepageId: text('notepage_id')
      .notNull()
      .references(() => notepages.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull(),
    col: integer('col').notNull(),
    row: integer('row').notNull(),
    colSpan: integer('col_span').notNull(),
    rowSpan: integer('row_span').notNull(),
    /** Author-picked theme shell option id (M6-D3); null = default shell. */
    shell: text('shell'),
    /** Block-level autofit mode (block-autofit-height): 'off' | 'grow' |
     * 'grow+shrink'; null = off/legacy. MVP writes/reads only 'grow' and
     * treats null/'off' as off. TEXT (not int-bool) so the A→three-state
     * upgrade is pure interpretation-widening, no second DDL migration. */
    autofit: text('autofit'),
    /** Author floor = minimum intended rowSpan (block-autofit-height);
     * null = off/legacy. Engine stays floor-blind; this is web/server
     * metadata, the `max(floor, fit)` reconcile reads it. */
    minRowSpan: integer('min_row_span'),
    content: text('content').notNull(),
  },
  (t) => [primaryKey({ columns: [t.notepageId, t.id] }), index('idx_blocks_notepage').on(t.notepageId)],
);

/**
 * Content-addressed blob registry (mvp2 M2-D3): hash = sha256 of bytes,
 * files live in the blob dir keyed by hash, rows are metadata only.
 * Immutable: a hash is never re-written; no GC in MVP-2 (surfaced debt).
 */
export const blobs = sqliteTable('blobs', {
  hash: text('hash').primaryKey(),
  mimeType: text('mime_type').notNull(),
  size: integer('size').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
});

/** Instance-level key-value settings (first instance setting: theme).
 * MVP-4 M4-D2; values are plain strings, callers own parsing. */
export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

export type NotepageRow = typeof notepages.$inferSelect;
export type BlockRow = typeof blocks.$inferSelect;

/** Shape of the publishedDoc JSON snapshot. */
export type PublishedDoc = {
  title: string;
  gravityEnabled: boolean;
  /** Author-picked page background (M6-D4); absent = theme canvas. */
  background?: { color?: string; blobHash?: string } | null;
  blocks: Array<{
    id: string;
    kind: string;
    col: number;
    row: number;
    colSpan: number;
    rowSpan: number;
    /** Author-picked theme shell option id (M6-D3). */
    shell?: string | null;
    /** Block-level autofit mode (block-autofit-height); null/absent = off. */
    autofit?: string | null;
    /** Author floor = minimum intended rowSpan; null/absent = off/legacy. */
    minRowSpan?: number | null;
    content: unknown;
  }>;
  publishedAt: number;
};
